//Получение контактов
export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_PENDING = 'GET_CONTACTS_PENDING';
export const GET_CONTACTS_FULFILLED = 'GET_CONTACTS_FULFILLED';
export const GET_CONTACTS_REJECTED = 'GET_CONTACTS_REJECTED';